### ISSUE TITLE
Card showing invalid status?

### ISSUE THREAD

**Issue by FS1961** [phrz/lg-washer-dryer-card#25] opened 2023-02-17 11:35 UTC
Hello,

Running the 31.3 LG integration and card is showing interesting things. First, I can't get the unit to show it's off/finished. The Wifi or sensing icon is on and the current course is really the last course it did. It is still showing 0:00:00 as the remaining time even though the unit is off? I must be stepping on something but not sure what. Not sure where to edit but I don't want to make it worse. This is an excellent integration - appreciate your hard work!

**_Please help!_**

p.s. - had to use a different font because the one you had referenced wasn't working for me for some reason - just fyi.

<img width="427" alt="Screenshot 2023-02-17 at 12 19 06 PM" src="https://user-images.githubusercontent.com/98458806/219636742-2590011e-f6d4-4edc-bafd-22f0feadae97.png">
<img width="1674" alt="Screenshot 2023-02-17 at 12 21 29 PM" src="https://user-images.githubusercontent.com/98458806/219637448-b3543277-bfcf-410d-aa5b-7a43201dcb54.png">

config.yml excerpt:
sensor:

  - platform: template
    sensors:
      washer_door_lock:
        friendly_name: "Washer Door Lock"
        value_template: "{{ state_attr('sensor.front_load_washer','door_lock') }}"

      washer_time_display:
        friendly_name: "Washer Time Display"
        value_template: >
          {% if is_state('sensor.front_load_washer_run_state', 'Finished') %}
          {% elif is_state('sensor.front_load_washer_run_state', 'Standby') %}
            -:--
          {% else %}
            {{ state_attr('sensor.front_load_washer', 'remain_time') }}
          {% endif %}

      blank:
        friendly_name: "Blank Sensor"
        value_template: ""

Template card:
type: vertical-stack
cards:
  - type: picture-elements
    elements:
      - type: image
        entity: sensor.front_load_washer_run_state
        image: local/community/lg-washer-card/lg-icons/sensing.png
        state_image:
          Detecting: local/community/lg-washer-card/lg-icons/sensing-on.png
        style:
          top: 33%
          left: 33%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.front_load_washer_run_state
        image: local/community/lg-washer-card/lg-icons/wash.png
        state_image:
          Washing: local/community/lg-washer-card/lg-icons/wash-on.png
        style:
          top: 33%
          left: 51%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.front_load_washer_run_state
        image: local/community/lg-washer-card/lg-icons/rinse.png
        state_image:
          Rinsing: local/community/lg-washer-card/lg-icons/rinse-on.png
        style:
          top: 33%
          left: 69%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.front_load_washer_run_state
        image: local/community/lg-washer-card/lg-icons/spin.png
        state_image:
          Spinning: local/community/lg-washer-card/lg-icons/spin-on.png
        style:
          top: 33%
          left: 87%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.front_load_washer
        image: local/community/lg-washer-card/lg-icons/wifi.png
        state_image:
          'on': local/community/lg-washer-card/lg-icons/wifi-on.png
        style:
          top: 73%
          left: 32%
          width: 10%
          image-rendering: crisp
      - type: image
        entity: sensor.front_load_washer_door_lock
        image: local/community/lg-washer-card/lg-icons/lock.png
        state_image:
          'on': local/community/lg-washer-card/lg-icons/lock-on.png
        style:
          top: 73%
          left: 45%
          width: 10%
          image-rendering: crisp
      - type: state-label
        entity: sensor.front_load_washer_remaining_time
        style:
          color: '#8df427'
          font-family: DJBGetDigital
          font-weight: normal
          font-size: 48px
          left: 95%
          top: 74%
          transform: translate(-100%,-50%)
    image: local/community/lg-washer-card/hass-combo-card-bg.png
  - type: conditional
    conditions:
      - entity: sensor.front_load_washer_run_state
        state_not: '-'
    card:
      type: entities
      entities:
        - entity: sensor.front_load_washer
          type: attribute
          attribute: current_course
          name: Current Course
          icon: mdi:tune-vertical-variant
        - entity: sensor.front_load_washer
          type: attribute
          attribute: water_temp
          name: Water Temperature
          icon: mdi:coolant-temperature
        - entity: sensor.front_load_washer
          type: attribute
          attribute: spin_speed
          name: Spin Speed
          icon: mdi:rotate-right
      state_color: false

**Comment by FS1961** [comment] 2023-02-17 17:46
@phrz - Thanks for the response. Actually, most of the states are in English. Kurz is just "short" which is a wash cycle type. I'm happy to do the work, I'm just not sure where. Please see the below attachment. Does this change anything?

<img width="164" alt="Screen Shot 2023-02-17 at 6 41 25 PM" src="https://user-images.githubusercontent.com/98458806/219732435-a2e572d5-4838-4a37-a7ea-dcf930b14506.png">

**Comment by phrz** [comment] 2023-02-17 19:44
Frank, thanks for giving me more context. I see now that your LG account is returning English strings via the ThinQ integration, so that is NOT the cause of the problem.

But I notice that the entities are still showing "0:00:00" as the Remaining time, that the Run state is "Finished", and so on, so my card is accurately reporting this information. In my experience, the Run state is supposed to change to "-", and that's when my card shows everything as "turned off." Because yours is not doing that, the card is not turning off. As far as I know, your washer *should* be leaving the "Finished" state and going into the "-" state, and if it's not, it's either a difference in your hardware, or something is amiss.

Is this screenshot from right after it finished, or is it from just now? Has the washer been used very recently? Did you go and turn your washer off when you were done? Did your ThinQ integration lose its connection, and never update? Are you running a very old version of the ThinQ integration? I'm running v0.31.2, according to HACS, and the latest version is v0.31.3.

**Comment by FS1961** [comment] 2023-02-17 20:02
@phrz - Actually, I'm also running 0.31.3.  The screen shot is current. The machine has been off (finished) for quite some time.
<img width="308" alt="Screen Shot 2023-02-17 at 8 56 45 PM" src="https://user-images.githubusercontent.com/98458806/219779140-93e76c09-c4eb-4528-a20e-6de99c40b845.png">
I'm going to run a load and see if anything changes.
<img width="301" alt="Screen Shot 2023-02-17 at 9 01 24 PM" src="https://user-images.githubusercontent.com/98458806/219781008-91a8d69c-244d-4d14-be43-dbc5e1708c50.png">
<img width="299" alt="Screen Shot 2023-02-17 at 9 01 34 PM" src="https://user-images.githubusercontent.com/98458806/219781045-527a5bb0-a289-4f2a-88f7-f612a5d2a900.png">

Looks correct during.

**Comment by FS1961** [comment] 2023-02-17 20:20
Oddly, it's not updating though.
![IMG_0088](https://user-images.githubusercontent.com/98458806/219785091-5c5164d7-be11-4f5f-bf76-7191220aece4.jpg)
<img width="304" alt="Screen Shot 2023-02-17 at 9 19 55 PM" src="https://user-images.githubusercontent.com/98458806/219785163-90ca932c-a72e-442b-abf0-55c785e8a74c.png">

**Comment by FS1961** [comment] 2023-02-17 20:32
Updated when it changed cycles:
<img width="254" alt="Screen Shot 2023-02-17 at 9 32 28 PM" src="https://user-images.githubusercontent.com/98458806/219787369-9127d347-87d7-4b6d-8782-23480f8c858f.png">

**Comment by FS1961** [comment] 2023-02-17 21:20
![IMG_7CF88944F50B-1](https://user-images.githubusercontent.com/98458806/219794684-8ef3b090-1a59-46bf-9d0c-891bebc580bb.jpeg)
![IMG_0092](https://user-images.githubusercontent.com/98458806/219795602-e78c9c1f-fc62-4e41-baaf-9acca410634f.jpg)
![IMG_0093](https://user-images.githubusercontent.com/98458806/219795615-99da3d48-e377-4fbf-bfc1-919a77dcf037.jpg)

It's weird because the unit has stopped but the app and integration haven't updated.

**Comment by FS1961** [comment] 2023-02-17 21:22
Maybe an issue with the LG service and not the integration or the card?

**Comment by phrz** [comment] 2023-02-17 21:23
I'm glad you were able to find where the issue lay: between the washer and the LG cloud, or possibly between the LG cloud and the integration. I'd recommend resetting your washer, or basically disconnecting the Wi-Fi and deleting it from the app, then re-adding it. Maybe check your router to see if the washer has poor signal strength. Otherwise, you can call LG, see if they will help (framed in the context of their official app, of course).

For now, I'll close the issue, because the bug doesn't seem to reside in this repository's implementation.

**Closed by phrz** 2023-02-17 21:23 UTC

**Comment by FS1961** [comment] 2023-02-18 06:35
Thanks for indulging me! I'll drop you a line/note to let you know what I find out.
